### ISSUE TITLE
Publish a beta npm package

### ISSUE THREAD

**Issue by nmetulev** [microsoftgraph/msgraph-beta-typescript-typings#1]
We (Microsoft Graph Toolkit) are currently consuming the beta types directly from github, but this is causing npm install errors for some of our users. Re: https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/174

Any chance you could publish a separate package for beta? 
AB#7038

**Comment by nikithauc** [comment]
I am excited to inform that we are working on the release of a beta typings package into the npm repository.

Followings are the steps for the migration -
1. Creation of a separate `microsoftgraph/msgraph-beta-typescript-typings` GitHub repo specific for the beta typings with the `main` branch.
2. Migrate from the `microsoftgraph/msgraph-typescript-typings#beta` branch to the `microsoftgraph/msgraph-beta-typescript-typings#main` maintaining the branch history. [Step followed](https://stackoverflow.com/questions/2227062/how-do-i-move-a-git-branch-out-into-its-own-repository).
3. Update `ReadMe.md` files in both the repository. Point to the new beta typings npm library once released and the new `microsoftgraph/msgraph-beta-typescript-typings` GitHub repo.
4. Reset the version in the beta repo package.json to '0.1.0-preview'. 
5.  Update the [generation pipeline](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/dev/.azure-pipelines/generation-pipeline.yml) -
* Change references pointing to `microsoftgraph/msgraph-typescript-typings#beta` branch to the `microsoftgraph/msgraph-beta-typescript-typings#main`
* Include the version auto increment logic in the generation process as a second commit. First commit being the generated typings file.
6. Add pipelines for -
* Production Build pipeline preparing the artifact to be published.
* Release pipeline publishing to the npm.
7. Tag and maintain the release history in GitHub releases.

**Comment by zengin** [comment]
8. Update GitHub Action that creates PRs to target main branch here.
9. Remove the special case from generation pipelines regarding branch naming. There was a conflict with creating a name with `beta/` because of the beta branch, we no longer have that problem, so we can align the branch naming with other SDKs now.

**Comment by nikithauc** [comment]
Npm package has been publish https://www.npmjs.com/package/@microsoft/microsoft-graph-types-beta !!
