### ISSUE TITLE
No Typing Updates (Again)

### ISSUE THREAD

**Issue by elliot-huffman** [microsoftgraph/msgraph-beta-typescript-typings#146]
The type generation system has stopped updating this repo with newer type specs.
Did another issue like the one that occurred in #80 ?

The specs provided are a little behind some of the new features and feature removals...

**Comment by elliot-huffman** [comment]
Pinging @koros and @nikithauc for visibility.

**Comment by elliot-huffman** [comment]
ping again! Still out of date...

**Comment by elliot-huffman** [comment]
@baywet , @koros , and @nikithauc .

Any updates? many new features were released during build and none of the types are available to take advantage properly.

**Comment by elliot-huffman** [comment]
@andrueastman Ping

**Comment by gshpychka** [comment]
@andrueastman is this library still supported by Microsoft?
