### ISSUE TITLE
Publish New Version

### ISSUE THREAD

**Issue by elliot-huffman** [microsoftgraph/msgraph-beta-typescript-typings#80]
Hi Team and @nikithauc,

I was trying to integrate my project with the new Authentication Strengths Policy in AAD Conditional Access, but the types were not updated.
Would you be able to update the NPM package to the latest API spec?

I also noticed that this project has not been updated in ~8 months. Would I be able to work with you all to create automatically publishing/updating NPM packages so that no work by hand is necessary?

That would fix the root cause of this issue, no updates to NPM...

Thanks!

**Comment by zengin** [comment]
Hi @elliot-huffman,

Thanks for raising the issue. TypeScript Beta type generation seems to be blocked on: https://github.com/microsoftgraph/msgraph-metadata/issues/154.

I see two potential solutions:
- Removal of the empty enum from metadata
- Adding a workaround for empty enums, i.e. skipping them in TypeScript typings output in the generation process. This doesn't seem to be a problem in other languages, although I am not aware of any use cases for empty enums.

Please note that the team is mostly away until the second week of January.

**Comment by elliot-huffman** [comment]
Thanks for the heads up!
I am just manually overriding the types for now to quiet my `TSC`, I look forward to the fix :-)

Since it appears to be from InTune devices, I'll shoot an email to my InTune CXP/CXE contact to see if I can get some additional traction. Otherwise Jan is fine with me.

**Comment by elliot-huffman** [comment]
Hi Team,

Checking in. (Bump)

Thanks!

**Comment by koros** [comment]
@elliot-huffman apologies for the delay I am currently looking into this, you should get an update soon. Thanks.

**Comment by elliot-huffman** [comment]
looks like it is live! thanks for the update :)

**Comment by koros** [comment]
@elliot-huffman thanks for your patience and apologies for the delay.
